In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import chart_studio.plotly as py
import cufflinks as cf
import plotly.express as px

pd.set_option('display.max_columns', None)
pd.options.display.float_format = '{:20,.2f}'.format

In [53]:
df = pd.read_csv('FIFA22_official_data.csv')
df

,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,Club Logo,Value,Wage,Special,Preferred Foot,International Reputation,Weak Foot,Skill Moves,Work Rate,Body Type,Real Face,Position,Jersey Number,Joined,Loaned From,Contract Valid Until,Height,Weight,Crossing,Finishing,HeadingAccuracy,ShortPassing,Volleys,Dribbling,Curve,FKAccuracy,LongPassing,BallControl,Acceleration,SprintSpeed,Agility,Reactions,Balance,ShotPower,Jumping,Stamina,Strength,LongShots,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Best Position,Best Overall Rating,Release Clause,DefensiveAwareness
0,212198,Bruno Fernandes,26,https://cdn.sofifa.com/players/212/198/22_60.png,Portugal,https://cdn.sofifa.com/flags/pt.png,88,89,Manchester United,https://cdn.sofifa.com/teams/11/30.png,€107.5M,€250K,2341,Right,3.00,3.00,4.00,High/ High,Unique,Yes,"<span class=""pos pos18"">CAM",18.00,"Jan 30, 2020",NaN,2025,179cm,69kg,87.00,83.00,64.00,91.00,87.00,83.00,87.00,87.00,88.00,87.00,77.00,73.00,80.00,91.00,79.00,89.00,73.00,91.00,70.00,89.00,78.00,66.00,87.00,90.00,91.00,87.00,NaN,73.00,65.00,12.00,14.00,15.00,8.00,14.00,CAM,88.00,€206.9M,72.00
1,209658,L. Goretzka,26,https://cdn.sofifa.com/players/209/658/22_60.png,Germany,https://cdn.sofifa.com/flags/de.png,87,88,FC Bayern München,https://cdn.sofifa.com/teams/21/30.png,€93M,€140K,2314,Right,4.00,4.00,3.00,High/ Medium,Unique,Yes,"<span class=""pos pos11"">LDM",8.00,"Jul 1, 2018",NaN,2026,189cm,82kg,75.00,82.00,86.00,86.00,69.00,84.00,76.00,75.00,84.00,87.00,78.00,83.00,76.00,88.00,71.00,85.00,79.00,88.00,88.00,86.00,81.00,86.00,85.00,84.00,60.00,82.00,NaN,85.00,77.00,13.00,8.00,15.00,11.00,9.00,CM,87.00,€160.4M,74.00
2,176580,L. Suárez,34,https://cdn.sofifa.com/players/176/580/22_60.png,Uruguay,https://cdn.sofifa.com/flags/uy.png,88,88,Atlético de Madrid,https://cdn.sofifa.com/teams/240/30.png,€44.5M,€135K,2307,Right,5.00,4.00,3.00,High/ Medium,Unique,Yes,"<span class=""pos pos24"">RS",9.00,"Sep 25, 2020",NaN,2022,182cm,83kg,80.00,93.00,84.00,83.00,90.00,83.00,86.00,82.00,77.00,86.00,76.00,69.00,75.00,92.00,78.00,89.00,69.00,78.00,85.00,88.00,87.00,41.00,91.00,84.00,83.00,87.00,NaN,45.00,38.00,27.00,25.00,31.00,33.00,37.00,ST,88.00,€91.2M,42.00
3,192985,K. De Bruyne,30,https://cdn.sofifa.com/players/192/985/22_60.png,Belgium,https://cdn.sofifa.com/flags/be.png,91,91,Manchester City,https://cdn.sofifa.com/teams/10/30.png,€125.5M,€350K,2304,Right,4.00,5.00,4.00,High/ High,Unique,Yes,"<span class=""pos pos13"">RCM",17.00,"Aug 30, 2015",NaN,2025,181cm,70kg,94.00,82.00,55.00,94.00,82.00,88.00,85.00,83.00,93.00,91.00,76.00,76.00,79.00,91.00,78.00,91.00,63.00,89.00,74.00,91.00,76.00,66.00,88.00,94.00,83.00,89.00,NaN,65.00,53.00,15.00,13.00,5.00,10.00,13.00,CM,91.00,€232.2M,68.00
4,224334,M. Acuña,29,https://cdn.sofifa.com/players/224/334/22_60.png,Argentina,https://cdn.sofifa.com/flags/ar.png,84,84,Sevilla FC,https://cdn.sofifa.com/teams/481/30.png,€37M,€45K,2292,Left,2.00,3.00,4.00,High/ High,Stocky (170-185),No,"<span class=""pos pos7"">LB",19.00,"Sep 14, 2020",NaN,2024,172cm,69kg,87.00,66.00,58.00,82.00,68.00,87.00,88.00,75.00,78.00,88.00,77.00,76.00,83.00,83.00,90.00,82.00,63.00,90.00,80.00,81.00,84.00,79.00,81.00,82.00,76.00,87.00,NaN,84.00,82.00,8.00,14.00,13.00,13.00,14.00,LB,84.00,€77.7M,80.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16705,240558,18 L. Clayton,17,https://cdn.sofifa.com/players/240/558/18_60.png,England,https://cdn.sofifa.com/flags/gb-eng.png,53,70,Cheltenham Town,https://cdn.sofifa.com/teams/1936/30.png,€100K,€1K,782,Right,1.00,2.00,1.00,Medium/ Medium,Normal (185+),No,"<span class=""pos pos29"">RES",31.00,"Jul 1, 2016",NaN,2019,188cm,80kg,12.00,5.00,13.00,18.00,7.00,12.00,11.00,13.00,19.00,10.00,15.00,21.00,34.00,30.00,31.00,16.00,51.00,26.00,57.00,6.00,16.00,9.00,5.00,29.00,18.00,37.00,5.00,11.00,12.00,55.00,54.00,52.00,50.00,59.00,GK,52.00,€238K,NaN
16706,262846,�. Dobre,20,https://cdn.sofifa.com/players/262/846/22_60.png,Romania,https://cdn.sofifa.com/flags/ro.png,53,63,FC Academica Clinceni,https://cdn.sofifa.com/teams/113391/30.png,€180K,€550,778,Right,1.00,2.00,1.00,Medium/ Medium,Normal (185+),No,"<span class=""pos pos29"">RES",1.00,"Jul 28, 2018",NaN,2025,194cm,86kg,13.00,7.00,10.00,17.00,7.00,6.00,11.00,13.00,28.00,17.00,16.00,22.00,30.00,38.00,24.00,40.00,35.00,24.00,32.00,6.00,18.00,13.00,8.00,33.00,12.00,29.00,NaN,13.00,12.00,57.00,52.00,53.00,48.00,58.00,GK,53.00,€279K,5.00
16707,241317,21 Xue Qinghao,19,https://cdn.sofifa.com/players/241/317/21_60.png,China PR,https://cdn.sofifa.com/flags/cn.png,47,60,Shanghai Shenhua FC,https://cdn.sofifa.com/teams/110955/30.png,€100K,€700,770,Right,1.00,2.00,1.00,Medium/ Medium,Lean (170-185),No,"<span class=""pos pos29"">RES",31.00,"Apr 19, 2021",NaN,2021,180cm,71kg,12.00,9.00,14.00,15.00,6.00,8.00,12.00,13.00,14.00,12.00,22.00,17.00,36.00,43.00,36.00,34.00,51.00,20.00,51.00,8.00,13.00,11.00,7.00,18.00,15.00,17.00,NaN,11.00,9.00,49.00,48.00,45.00,38.00,52.00,GK,47.00,€223K,21.00
16708,259646,A. Shaikh,18,https://cdn.sofifa.com/players/259/646/22_60.png,India,https://cdn.sofifa.com/flags/in.png,47,67,ATK Mohun Bagan FC,https://cdn.sofifa.com/teams/113146/30.png,€110K,€500,754,Right,1.00,3.00,1.00,Medium/ Medium,Normal (185+),No,"<span class=""pos pos28"">SUB",31.00,"Aug 1, 2020",NaN,2022,186cm,74kg,13.00,8.00,10.00,22.00,8.00,10.00,11.00,13.00,18.00,13.00,20.00,18.00,26.00,45.00,44.00,29.00,45.00,19.00,34.00,5.00,24.00,6.00,6.00,31.00,19.00,23.00,NaN,14.00,13.00,49.00,41.00,39.00,45.00,49.00,GK,47.00,€259K,7.00
16709,178453,07 A. Censori,17,https://cdn.sofifa.com/players/178/453/07_60.png,Italy,https://cdn.sofifa.com/flags/it.png,28,38,Arezzo,https://cdn.sofifa.com/teams/110907/30.png,€0,€0,571,Right,1.00,2.00,1.00,N/A/ N/A,NaN,NaN,"<span class=""pos pos28"">SUB",88.00,NaN,NaN,2008,177cm,69kg,34.00,39.00,29.00,32.00,NaN,29.00,NaN,11.00,36.00,34.00,43.00,48.00,NaN,41.00,NaN,39.00,NaN,13.00,18.00,36.00,24.00,NaN,NaN,NaN,11.00,NaN,15.00,16.00,NaN,7.00,1.00,36.00,6.00,9.00,ST,36.00,NaN,NaN

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16710 entries, 0 to 16709
Data columns (total 65 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        16710 non-null  int64
 1   Name                      16710 non-null  object
 2   Age                       16710 non-null  int64
 3   Photo                     16710 non-null  object
 4   Nationality               16710 non-null  object
 5   Flag                      16710 non-null  object
 6   Overall                   16710 non-null  int64
 7   Potential                 16710 non-null  int64
 8   Club                      16446 non-null  object
 9   Club Logo                 16710 non-null  object
 10  Value                     16710 non-null  object
 11  Wage                      16710 non-null  object
 12  Special                   16710 non-null  int64
 13  Preferred Foot            16710 non-null  object
 14  International Reputation  16710 non-null  float64
 15  Weak Foot                 16710 non-null  float64
 16  Skill Moves               16710 non-null  float64
 17  Work Rate                 16710 non-null  object
 18  Body Type                 16681 non-null  object
 19  Real Face                 16681 non-null  object
 20  Position                  16684 non-null  object
 21  Jersey Number             16684 non-null  float64
 22  Joined                    15198 non-null  object
 23  Loaned From               1132 non-null   object
 24  Contract Valid Until      16359 non-null  object
 25  Height                    16710 non-null  object
 26  Weight                    16710 non-null  object
 27  Crossing                  16710 non-null  float64
 28  Finishing                 16710 non-null  float64
 29  HeadingAccuracy           16710 non-null  float64
 30  ShortPassing              16710 non-null  float64
 31  Volleys                   16673 non-null  float64
 32  Dribbling                 16710 non-null  float64
 33  Curve                     16673 non-null  float64
 34  FKAccuracy                16710 non-null  float64
 35  LongPassing               16710 non-null  float64
 36  BallControl               16710 non-null  float64
 37  Acceleration              16710 non-null  float64
 38  SprintSpeed               16710 non-null  float64
 39  Agility                   16673 non-null  float64
 40  Reactions                 16710 non-null  float64
 41  Balance                   16673 non-null  float64
 42  ShotPower                 16710 non-null  float64
 43  Jumping                   16673 non-null  float64
 44  Stamina                   16710 non-null  float64
 45  Strength                  16710 non-null  float64
 46  LongShots                 16710 non-null  float64
 47  Aggression                16710 non-null  float64
 48  Interceptions             16702 non-null  float64
 49  Positioning               16702 non-null  float64
 50  Vision                    16673 non-null  float64
 51  Penalties                 16710 non-null  float64
 52  Composure                 16459 non-null  float64
 53  Marking                   892 non-null    float64
 54  StandingTackle            16710 non-null  float64
 55  SlidingTackle             16673 non-null  float64
 56  GKDiving                  16710 non-null  float64
 57  GKHandling                16710 non-null  float64
 58  GKKicking                 16710 non-null  float64
 59  GKPositioning             16710 non-null  float64
 60  GKReflexes                16710 non-null  float64
 61  Best Position             16710 non-null  object
 62  Best Overall Rating       16710 non-null  float64
 63  Release Clause            14961 non-null  object
 64  DefensiveAwareness        15818 non-null  float64
dtypes: float64(40), int64(5), object(20)
memory usage: 8.3+ MB

In [55]:
df_extra_info = df[['ID','Photo', 'Flag', 'Club Logo', 'Real Face']]
df.drop(columns=['Photo', 'Flag', 'Club Logo', 'Real Face'], inplace=True)
df_extra_info

,ID,Photo,Flag,Club Logo,Real Face
0,212198,https://cdn.sofifa.com/players/212/198/22_60.png,https://cdn.sofifa.com/flags/pt.png,https://cdn.sofifa.com/teams/11/30.png,Yes
1,209658,https://cdn.sofifa.com/players/209/658/22_60.png,https://cdn.sofifa.com/flags/de.png,https://cdn.sofifa.com/teams/21/30.png,Yes
2,176580,https://cdn.sofifa.com/players/176/580/22_60.png,https://cdn.sofifa.com/flags/uy.png,https://cdn.sofifa.com/teams/240/30.png,Yes
3,192985,https://cdn.sofifa.com/players/192/985/22_60.png,https://cdn.sofifa.com/flags/be.png,https://cdn.sofifa.com/teams/10/30.png,Yes
4,224334,https://cdn.sofifa.com/players/224/334/22_60.png,https://cdn.sofifa.com/flags/ar.png,https://cdn.sofifa.com/teams/481/30.png,No
...,...,...,...,...,...
16705,240558,https://cdn.sofifa.com/players/240/558/18_60.png,https://cdn.sofifa.com/flags/gb-eng.png,https://cdn.sofifa.com/teams/1936/30.png,No
16706,262846,https://cdn.sofifa.com/players/262/846/22_60.png,https://cdn.sofifa.com/flags/ro.png,https://cdn.sofifa.com/teams/113391/30.png,No
16707,241317,https://cdn.sofifa.com/players/241/317/21_60.png,https://cdn.sofifa.com/flags/cn.png,https://cdn.sofifa.com/teams/110955/30.png,No
16708,259646,https://cdn.sofifa.com/players/259/646/22_60.png,https://cdn.sofifa.com/flags/in.png,https://cdn.sofifa.com/teams/113146/30.png,No
16709,178453,https://cdn.sofifa.com/players/178/453/07_60.png,https://cdn.sofifa.com/flags/it.png,https://cdn.sofifa.com/teams/110907/30.png,NaN

In [56]:
df.isna().sum().sort_values(ascending=False).head(25)

Marking                 15818
Loaned From             15578
Release Clause           1749
Joined                   1512
DefensiveAwareness        892
Contract Valid Until      351
Club                      264
Composure                 251
Agility                    37
Balance                    37
Jumping                    37
Curve                      37
Volleys                    37
Vision                     37
SlidingTackle              37
Body Type                  29
Jersey Number              26
Position                   26
Positioning                 8
Interceptions               8
GKPositioning               0
Best Overall Rating         0
ShotPower                   0
Best Position               0
Stamina                     0
dtype: int64

In [57]:
df[['Name', 'Wage']].sort_values('Wage',ascending=False)

                Name Wage
8771           Rober  €9K
3132      Igor Silva  €9K
10418   F. Bonazzoli  €9K
14160      J. Chabot  €9K
5126         A. Long  €9K
...              ...  ...
2570     16 D. Agger   €0
546        M. Ozdoev   €0
2595        21 Afsha   €0
6502      N. Nikolić   €0
16709  07 A. Censori   €0

[16710 rows x 2 columns]

In [58]:
df['Position'].value_counts().reset_index(name = 'count')

                          index  count
0   <span class="pos pos28">SUB   7192
1   <span class="pos pos29">RES   2705
2    <span class="pos pos4">RCB    611
3    <span class="pos pos6">LCB    609
4     <span class="pos pos0">GK    572
5    <span class="pos pos25">ST    466
6     <span class="pos pos3">RB    438
7     <span class="pos pos7">LB    423
8   <span class="pos pos13">RCM    398
9   <span class="pos pos15">LCM    395
10   <span class="pos pos12">RM    361
11   <span class="pos pos16">LM    358
12  <span class="pos pos18">CAM    283
13   <span class="pos pos24">RS    219
14   <span class="pos pos26">LS    216
15   <span class="pos pos9">RDM    204
16  <span class="pos pos11">LDM    191
17   <span class="pos pos27">LW    185
18   <span class="pos pos23">RW    175
19  <span class="pos pos10">CDM    160
20    <span class="pos pos5">CB    150
21   <span class="pos pos2">RWB     95
22   <span class="pos pos8">LWB     92
23   <span class="pos pos14">CM     75
24   <span class="pos pos20">RF     31
25   <span class="pos pos22">LF     30
26  <span class="pos pos19">LAM     22
27  <span class="pos pos17">RAM     17
28   <span class="pos pos21">CF     11

In [59]:
df['Best Position'].value_counts().reset_index(name = 'count')

   index  count
0     CB   3214
1     ST   2549
2    CAM   2203
3     GK   1546
4     RM   1313
5    CDM   1262
6     CM   1011
7     RB    856
8     LB    813
9     LM    745
10    RW    335
11   RWB    310
12   LWB    289
13    LW    182
14    CF     82

### Cleaning columns with Currency, height and weight

In [60]:
df['Wage'] = df['Wage'].replace({'€': '', ',': '', 'K':'000', '\.':''}, regex=True).astype(float)
df['Wage']

0                 250,000.00
1                 140,000.00
2                 135,000.00
3                 350,000.00
4                  45,000.00
                ...
16705               1,000.00
16706                 550.00
16707                 700.00
16708                 500.00
16709                   0.00
Name: Wage, Length: 16710, dtype: float64

In [61]:
df[['Name', 'Wage']].sort_values('Wage',ascending=False).head(20)

                    Name                 Wage
3           K. De Bruyne           350,000.00
201           K. Benzema           350,000.00
29              L. Messi           320,000.00
28              Casemiro           310,000.00
116             T. Kroos           310,000.00
220          R. Sterling           290,000.00
64             Neymar Jr           270,000.00
55               S. Mané           270,000.00
36     Cristiano Ronaldo           270,000.00
34              M. Salah           270,000.00
33        R. Lewandowski           270,000.00
396            S. Agüero           260,000.00
425            R. Lukaku           260,000.00
14937        T. Courtois           250,000.00
13890      M. ter Stegen           250,000.00
0        Bruno Fernandes           250,000.00
39               H. Kane           240,000.00
486            E. Hazard           240,000.00
82             K. Mbappé           230,000.00
71              N. Kanté           230,000.00

In [62]:
df['Release Clause'] = df['Release Clause'].replace({'€': '', ',': '', 'K':'000','M':'000000', '\.':''}, regex=True).astype(float)
df['Value'] = df['Value'].replace({'€': '', ',': '', 'K':'000', 'M':'000000', '\.':''}, regex=True).astype(float)
df['Weight'] = df['Weight'].replace({'kg':''}, regex=True).astype(float)
df['Height'] = df['Height'].replace({'cm':''}, regex=True).astype(float)

In [63]:
df

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Special,Preferred Foot,International Reputation,Weak Foot,Skill Moves,Work Rate,Body Type,Position,Jersey Number,Joined,Loaned From,Contract Valid Until,Height,Weight,Crossing,Finishing,HeadingAccuracy,ShortPassing,Volleys,Dribbling,Curve,FKAccuracy,LongPassing,BallControl,Acceleration,SprintSpeed,Agility,Reactions,Balance,ShotPower,Jumping,Stamina,Strength,LongShots,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Best Position,Best Overall Rating,Release Clause,DefensiveAwareness
0,212198,Bruno Fernandes,26,Portugal,88,89,Manchester United,"1,075,000,000.00","250,000.00",2341,Right,3.00,3.00,4.00,High/ High,Unique,"<span class=""pos pos18"">CAM",18.00,"Jan 30, 2020",NaN,2025,179.00,69.00,87.00,83.00,64.00,91.00,87.00,83.00,87.00,87.00,88.00,87.00,77.00,73.00,80.00,91.00,79.00,89.00,73.00,91.00,70.00,89.00,78.00,66.00,87.00,90.00,91.00,87.00,NaN,73.00,65.00,12.00,14.00,15.00,8.00,14.00,CAM,88.00,"2,069,000,000.00",72.00
1,209658,L. Goretzka,26,Germany,87,88,FC Bayern München,"93,000,000.00","140,000.00",2314,Right,4.00,4.00,3.00,High/ Medium,Unique,"<span class=""pos pos11"">LDM",8.00,"Jul 1, 2018",NaN,2026,189.00,82.00,75.00,82.00,86.00,86.00,69.00,84.00,76.00,75.00,84.00,87.00,78.00,83.00,76.00,88.00,71.00,85.00,79.00,88.00,88.00,86.00,81.00,86.00,85.00,84.00,60.00,82.00,NaN,85.00,77.00,13.00,8.00,15.00,11.00,9.00,CM,87.00,"1,604,000,000.00",74.00
2,176580,L. Suárez,34,Uruguay,88,88,Atlético de Madrid,"445,000,000.00","135,000.00",2307,Right,5.00,4.00,3.00,High/ Medium,Unique,"<span class=""pos pos24"">RS",9.00,"Sep 25, 2020",NaN,2022,182.00,83.00,80.00,93.00,84.00,83.00,90.00,83.00,86.00,82.00,77.00,86.00,76.00,69.00,75.00,92.00,78.00,89.00,69.00,78.00,85.00,88.00,87.00,41.00,91.00,84.00,83.00,87.00,NaN,45.00,38.00,27.00,25.00,31.00,33.00,37.00,ST,88.00,"912,000,000.00",42.00
3,192985,K. De Bruyne,30,Belgium,91,91,Manchester City,"1,255,000,000.00","350,000.00",2304,Right,4.00,5.00,4.00,High/ High,Unique,"<span class=""pos pos13"">RCM",17.00,"Aug 30, 2015",NaN,2025,181.00,70.00,94.00,82.00,55.00,94.00,82.00,88.00,85.00,83.00,93.00,91.00,76.00,76.00,79.00,91.00,78.00,91.00,63.00,89.00,74.00,91.00,76.00,66.00,88.00,94.00,83.00,89.00,NaN,65.00,53.00,15.00,13.00,5.00,10.00,13.00,CM,91.00,"2,322,000,000.00",68.00
4,224334,M. Acuña,29,Argentina,84,84,Sevilla FC,"37,000,000.00","45,000.00",2292,Left,2.00,3.00,4.00,High/ High,Stocky (170-185),"<span class=""pos pos7"">LB",19.00,"Sep 14, 2020",NaN,2024,172.00,69.00,87.00,66.00,58.00,82.00,68.00,87.00,88.00,75.00,78.00,88.00,77.00,76.00,83.00,83.00,90.00,82.00,63.00,90.00,80.00,81.00,84.00,79.00,81.00,82.00,76.00,87.00,NaN,84.00,82.00,8.00,14.00,13.00,13.00,14.00,LB,84.00,"777,000,000.00",80.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16705,240558,18 L. Clayton,17,England,53,70,Cheltenham Town,"100,000.00","1,000.00",782,Right,1.00,2.00,1.00,Medium/ Medium,Normal (185+),"<span class=""pos pos29"">RES",31.00,"Jul 1, 2016",NaN,2019,188.00,80.00,12.00,5.00,13.00,18.00,7.00,12.00,11.00,13.00,19.00,10.00,15.00,21.00,34.00,30.00,31.00,16.00,51.00,26.00,57.00,6.00,16.00,9.00,5.00,29.00,18.00,37.00,5.00,11.00,12.00,55.00,54.00,52.00,50.00,59.00,GK,52.00,"238,000.00",NaN
16706,262846,�. Dobre,20,Romania,53,63,FC Academica Clinceni,"180,000.00",550.00,778,Right,1.00,2.00,1.00,Medium/ Medium,Normal (185+),"<span class=""pos pos29"">RES",1.00,"Jul 28, 2018",NaN,2025,194.00,86.00,13.00,7.00,10.00,17.00,7.00,6.00,11.00,13.00,28.00,17.00,16.00,22.00,30.00,38.00,24.00,40.00,35.00,24.00,32.00,6.00,18.00,13.00,8.00,33.00,12.00,29.00,NaN,13.00,12.00,57.00,52.00,53.00,48.00,58.00,GK,53.00,"279,000.00",5.00
16707,241317,21 Xue Qinghao,19,China PR,47,60,Shanghai Shenhua FC,"100,000.00",700.00,770,Right,1.00,2.00,1.00,Medium/ Medium,Lean (170-185),"<span class=""pos pos29"">RES",31.00,"Apr 19, 2021",NaN,2021,180.00,71.00,12.00,9.00,14.00,15.00,6.00,8.00,12.00,13.00,14.00,12.00,22.00,17.00,36.00,43.00,36.00,34.00,51.00,20.00,51.00,8.00,13.00,11.00,7.00,18.00,15.00,17.00,NaN,11.00,9.00,49.00,48.00,45.00,38.00,52.00,GK,47.00,"223,000.00",21.00
16708,259646,A. Shaikh,18,India,47,67,ATK Mohun Bagan FC,"110,000.00",500.00,754,Right,1.00,3.00,1.00,Medium/ Medium,Normal (185+),"<span class=""pos pos28"">SUB",31.00,"Aug 1, 2020",NaN,2022,186.00,74.00,13.00,8.00,10.00,22.00,8.00,10.00,11.00,13.00,18.00,13.00,20.00,18.00,26.00,45.00,44.00,29.00,45.00,19.00,34.00,5.00,24.00,6.00,6.00,31.00,19.00,23.00,NaN,14.00,13.00,49.00,41.00,39.00,45.00,49.00,GK,47.00,"259,000.00",7.00
16709,178453,07 A. Censori,17,Italy,28,38,Arezzo,0.00,0.00,571,Right,1.00,2.00,1.00,N/A/ N/A,NaN,"<span class=""pos pos28"">SUB",88.00,NaN,NaN,2008,177.00,69.00,34.00,39.00,29.00,32.00,NaN,29.00,NaN,11.00,36.00,34.00,43.00,48.00,NaN,41.00,NaN,39.00,NaN,13.00,18.00,36.00,24.00,NaN,NaN,NaN,11.00,NaN,15.00,16.00,NaN,7.00,1.00,36.00,6.00,9.00,ST,36.00,NaN,NaN

In [64]:
df.describe()

,ID,Age,Overall,Potential,Value,Wage,Special,International Reputation,Weak Foot,Skill Moves,Jersey Number,Height,Weight,Crossing,Finishing,HeadingAccuracy,ShortPassing,Volleys,Dribbling,Curve,FKAccuracy,LongPassing,BallControl,Acceleration,SprintSpeed,Agility,Reactions,Balance,ShotPower,Jumping,Stamina,Strength,LongShots,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Best Overall Rating,Release Clause,DefensiveAwareness
count,"16,710.00","16,710.00","16,710.00","16,710.00","16,710.00","16,710.00","16,710.00","16,710.00","16,710.00","16,710.00","16,684.00","16,710.00","16,710.00","16,710.00","16,710.00","16,710.00","16,710.00","16,673.00","16,710.00","16,673.00","16,710.00","16,710.00","16,710.00","16,710.00","16,710.00","16,673.00","16,710.00","16,673.00","16,710.00","16,673.00","16,710.00","16,710.00","16,710.00","16,710.00","16,702.00","16,702.00","16,673.00","16,710.00","16,459.00",892.00,"16,710.00","16,673.00","16,710.00","16,710.00","16,710.00","16,710.00","16,710.00","16,710.00","14,961.00","15,818.00"
mean,"220,560.47",25.73,67.65,72.57,"20,880,862.36","11,338.93","1,652.50",1.17,3.01,2.48,20.46,181.43,75.29,52.21,48.73,54.12,61.31,45.65,58.59,50.57,45.07,55.45,61.39,65.68,65.78,65.22,63.59,64.94,60.64,65.90,64.20,66.27,49.99,57.96,48.06,53.15,56.38,50.62,61.00,48.02,49.16,46.83,15.68,15.52,15.46,15.58,15.79,68.57,"58,119,675.69",48.02
std,"38,496.61",5.05,6.46,5.69,"59,142,512.29","21,309.54",257.27,0.49,0.68,0.79,17.70,6.87,7.16,17.77,19.40,17.01,13.67,17.83,17.93,18.24,17.60,14.49,15.67,15.01,14.74,14.51,8.59,14.26,12.96,12.29,15.58,12.62,19.08,16.86,20.85,19.20,13.42,15.76,11.40,21.90,21.45,21.18,17.01,16.30,16.10,16.58,17.32,6.26,"155,300,105.63",20.18
min,27.00,16.00,28.00,38.00,0.00,0.00,571.00,1.00,1.00,1.00,1.00,155.00,49.00,7.00,3.00,5.00,8.00,4.00,5.00,6.00,4.00,9.00,8.00,13.00,15.00,18.00,28.00,19.00,12.00,22.00,13.00,18.00,4.00,11.00,4.00,3.00,10.00,7.00,12.00,4.00,3.00,6.00,1.00,1.00,1.00,1.00,1.00,36.00,"14,000.00",3.00
25%,"203,891.25",22.00,63.00,69.00,"600,000.00","2,000.00","1,525.00",1.00,3.00,2.00,8.00,176.25,70.00,42.00,34.00,46.00,57.00,33.00,54.00,39.00,33.00,47.00,58.00,58.00,59.00,57.00,58.00,57.00,52.00,59.00,57.00,59.00,37.00,47.00,28.00,44.00,48.00,41.00,55.00,27.00,29.00,26.00,8.00,8.00,8.00,8.00,8.00,65.00,"2,000,000.00",30.00
50%,"229,253.00",25.00,68.00,72.00,"11,000,000.00","4,000.00","1,687.00",1.00,3.00,2.00,17.00,182.00,75.00,57.00,53.00,57.00,64.00,48.00,63.50,53.00,44.00,58.00,65.00,68.00,68.00,68.00,64.00,67.00,62.00,67.00,67.00,68.00,55.00,61.00,55.00,58.00,58.00,52.00,62.00,53.00,57.00,54.00,11.00,11.00,11.00,11.00,11.00,68.00,"19,000,000.00",54.00
75%,"245,368.75",29.00,72.00,76.00,"21,000,000.00","12,000.00","1,826.00",1.00,3.00,3.00,27.00,186.00,80.00,65.00,64.00,66.00,70.00,59.00,70.00,64.00,59.00,66.00,71.00,76.00,76.00,75.00,69.00,75.00,70.00,74.00,75.00,75.00,65.00,71.00,65.00,67.00,66.00,62.00,69.00,67.00,67.00,65.00,14.00,14.00,14.00,14.00,14.00,73.00,"44,000,000.00",65.00
max,"264,704.00",54.00,93.00,95.00,"1,375,000,000.00","350,000.00","2,341.00",5.00,5.00,5.00,99.00,206.00,110.00,94.00,95.00,93.00,94.00,90.00,96.00,94.00,94.00,93.00,96.00,97.00,97.00,96.00,96.00,96.00,95.00,95.00,97.00,97.00,94.00,95.00,95.00,96.00,95.00,96.00,96.00,94.00,93.00,95.00,91.00,92.00,93.00,93.00,90.00,93.00,"3,735,000,000.00",93.00

In [74]:
df.groupby('Club').sum()['Value'].reset_index().sort_values('Value', ascending = False).head(20)

                    Club                Value
525      Manchester City     8,919,595,000.00
526    Manchester United     8,638,931,000.00
592  Paris Saint-Germain     7,056,700,000.00
177              Chelsea     6,243,725,000.00
312    FC Bayern München     4,883,875,000.00
637       Real Madrid CF     4,882,750,000.00
780    Tottenham Hotspur     4,742,700,000.00
87    Atlético de Madrid     4,597,900,000.00
511            Liverpool     4,448,300,000.00
12              AC Milan     4,230,375,000.00
309         FC Barcelona     4,105,000,000.00
116    Borussia Dortmund     3,397,600,000.00
455                Inter     3,359,861,000.00
505       Leicester City     3,143,310,000.00
467             Juventus     3,140,000,000.00
715           Sevilla FC     3,105,000,000.00
73               Arsenal     3,039,300,000.00
298              Everton     2,892,210,000.00
551               Napoli     2,886,600,000.00
618           RB Leipzig     2,851,255,000.00

In [75]:
df.groupby('Club').sum()['Wage'].reset_index().sort_values('Wage', ascending = False).head(20)

                    Club                 Wage
637       Real Madrid CF         4,487,000.00
526    Manchester United         3,754,000.00
309         FC Barcelona         3,725,000.00
525      Manchester City         3,641,100.00
511            Liverpool         3,326,000.00
592  Paris Saint-Germain         3,325,500.00
177              Chelsea         3,089,000.00
455                Inter         2,872,000.00
312    FC Bayern München         2,483,000.00
505       Leicester City         2,359,500.00
467             Juventus         2,277,000.00
780    Tottenham Hotspur         2,203,000.00
73               Arsenal         2,118,400.00
87    Atlético de Madrid         2,091,000.00
298              Everton         2,038,500.00
498                Lazio         1,879,500.00
843      West Ham United         1,677,250.00
12              AC Milan         1,618,000.00
551               Napoli         1,555,000.00
116    Borussia Dortmund         1,483,000.00

In [122]:
df.groupby('Club').mean()['Best Overall Rating'].reset_index().sort_values('Best Overall Rating', ascending = False).head(20)

                                Club              Overall
8                             111648                87.00
306             FC Anzhi Makhachkala                79.00
729                            Siena                79.00
312                FC Bayern München                78.85
467                         Juventus                78.73
592              Paris Saint-Germain                78.59
526                Manchester United                78.05
329                     FC Krasnodar                78.00
87                Atlético de Madrid                77.41
551                           Napoli                77.22
309                     FC Barcelona                77.03
685                       SL Benfica                76.89
378                         Flamengo                76.82
455                            Inter                76.67
464                       Jiangsu FC                76.50
741  Sport Club Corinthians Paulista                76.29
177                          Chelsea                76.17
511                        Liverpool                76.14
637                   Real Madrid CF                76.05
641                    Real Sociedad                76.03

### Best Squad

In [102]:
positions = df['Best Position'].unique()
positions

array(['CAM', 'CM', 'ST', 'LB', 'CDM', 'CB', 'RB', 'LM', 'RW', 'LW', 'CF',
       'LWB', 'RM', 'RWB', 'GK'], dtype=object)

In [137]:
best_player = pd.concat([pd.DataFrame(pd.DataFrame(df[df['Best Position'] == positions[i]]).sort_values('Best Overall Rating', ascending=False).iloc[0:1]) for i in range(len(positions))],
          ignore_index=True)
best_player

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Special,Preferred Foot,International Reputation,Weak Foot,Skill Moves,Work Rate,Body Type,Position,Jersey Number,Joined,Loaned From,Contract Valid Until,Height,Weight,Crossing,Finishing,HeadingAccuracy,ShortPassing,Volleys,Dribbling,Curve,FKAccuracy,LongPassing,BallControl,Acceleration,SprintSpeed,Agility,Reactions,Balance,ShotPower,Jumping,Stamina,Strength,LongShots,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Best Position,Best Overall Rating,Release Clause,DefensiveAwareness
0,211110,P. Dybala,27,Argentina,87,88,Juventus,"93,000,000.00","160,000.00",2134,Left,3.00,3.00,4.00,Medium/ Medium,Unique,"<span class=""pos pos18"">CAM",10.00,"Jul 1, 2015",NaN,2022,177.00,75.00,82.00,85.00,59.00,87.00,88.00,90.00,90.00,88.00,79.00,93.00,88.00,80.00,92.00,80.00,94.00,84.00,75.00,70.00,61.00,89.00,43.00,42.00,82.00,91.00,84.00,79.00,NaN,41.00,39.00,5.00,4.00,4.00,5.00,8.00,CAM,89.00,"1,604,000,000.00",32.00
1,192985,K. De Bruyne,30,Belgium,91,91,Manchester City,"1,255,000,000.00","350,000.00",2304,Right,4.00,5.00,4.00,High/ High,Unique,"<span class=""pos pos13"">RCM",17.00,"Aug 30, 2015",NaN,2025,181.00,70.00,94.00,82.00,55.00,94.00,82.00,88.00,85.00,83.00,93.00,91.00,76.00,76.00,79.00,91.00,78.00,91.00,63.00,89.00,74.00,91.00,76.00,66.00,88.00,94.00,83.00,89.00,NaN,65.00,53.00,15.00,13.00,5.00,10.00,13.00,CM,91.00,"2,322,000,000.00",68.00
2,231747,K. Mbappé,22,France,91,95,Paris Saint-Germain,"194,000,000.00","230,000.00",2175,Right,4.00,4.00,5.00,High/ Low,Unique,"<span class=""pos pos25"">ST",7.00,"Jul 1, 2018",NaN,2022,182.00,73.00,78.00,93.00,72.00,85.00,83.00,93.00,80.00,69.00,71.00,91.00,97.00,97.00,92.00,93.00,83.00,86.00,78.00,88.00,77.00,82.00,62.00,38.00,92.00,82.00,79.00,88.00,NaN,34.00,32.00,13.00,5.00,7.00,11.00,6.00,ST,92.00,"3,735,000,000.00",26.00
3,216267,A. Robertson,27,Scotland,87,88,Liverpool,"835,000,000.00","175,000.00",2163,Left,3.00,2.00,3.00,High/ High,Unique,"<span class=""pos pos7"">LB",26.00,"Jul 21, 2017",NaN,2026,178.00,64.00,88.00,55.00,67.00,82.00,32.00,81.00,82.00,71.00,76.00,83.00,83.00,85.00,78.00,85.00,74.00,76.00,62.00,95.00,65.00,65.00,85.00,83.00,77.00,80.00,55.00,83.00,NaN,84.00,81.00,11.00,8.00,10.00,7.00,14.00,LB,87.00,"1,607,000,000.00",83.00
4,215914,N. Kanté,30,France,90,90,Chelsea,"100,000,000.00","230,000.00",2179,Right,4.00,3.00,2.00,Medium/ High,Unique,"<span class=""pos pos13"">RCM",7.00,"Jul 16, 2016",NaN,2023,168.00,70.00,68.00,65.00,54.00,82.00,56.00,79.00,49.00,49.00,79.00,81.00,82.00,75.00,82.00,93.00,92.00,71.00,77.00,97.00,72.00,65.00,93.00,91.00,72.00,78.00,54.00,84.00,NaN,93.00,86.00,15.00,12.00,10.00,7.00,10.00,CDM,90.00,"185,000,000.00",90.00
5,207865,Marquinhos,27,Brazil,87,90,Paris Saint-Germain,"905,000,000.00","135,000.00",2074,Right,3.00,3.00,3.00,Medium/ High,Normal (170-185),"<span class=""pos pos4"">RCB",5.00,"Jul 19, 2013",NaN,2024,183.00,75.00,68.00,51.00,88.00,84.00,35.00,69.00,58.00,32.00,85.00,79.00,81.00,81.00,69.00,87.00,67.00,65.00,92.00,83.00,78.00,45.00,81.00,88.00,68.00,74.00,52.00,86.00,NaN,89.00,89.00,6.00,6.00,12.00,10.00,13.00,CB,89.00,"1,742,000,000.00",89.00
6,231281,T. Alexander-Arnold,22,England,87,92,Liverpool,"114,000,000.00","150,000.00",2227,Right,3.00,4.00,3.00,High/ Medium,Unique,"<span class=""pos pos3"">RB",66.00,"Oct 7, 2015",NaN,2025,180.00,69.00,92.00,60.00,69.00,86.00,62.00,78.00,87.00,85.00,90.00,86.00,77.00,80.00,73.00,82.00,73.00,82.00,66.00,88.00,63.00,75.00,74.00,82.00,77.00,87.00,55.00,81.00,NaN,83.00,79.00,14.00,15.00,14.00,6.00,7.00,RB,87.00,"2,195,000,000.00",80.00
7,200104,H. Son,28,Korea Republic,89,89,Tottenham Hotspur,"104,000,000.00","220,000.00",2142,Right,4.00,5.00,4.00,High/ High,Unique,"<span class=""pos pos27"">LW",7.00,"Aug 28, 2015",NaN,2025,183.00,78.00,83.00,88.00,68.00,84.00,78.00,87.00,85.00,74.00,74.00,84.00,85.00,90.00,86.00,91.00,78.00,88.00,60.00,88.00,64.00,89.00,62.00,39.00,91.00,83.00,73.00,89.00,NaN,34.00,33.00,11.00,13.00,13.00,6.00,10.00,LM,89.00,"1,976,000,000.00",50.00
8,158023,L. Messi,34,Argentina,93,93,Paris Saint-Germain,"78,000,000.00","320,000.00",2219,Left,5.00,4.00,4.00,Medium/ Low,Unique,"<span class=""pos pos23"">RW",30.00,"Aug 10, 2021",NaN,2023,170.00,72.00,85.00,95.00,70.00,91.00,88.00,96.00,93.00,94.00,91.00,96.00,91.00,80.00,91.00,94.00,95.00,86.00,68.00,72.00,69.00,94.00,44.00,40.00,93.00,95.00,75.00,96.00,NaN,35.00,24.00,6.00,11.00,15.00,14.00,8.00,RW,93.00,"1,443,000,000.00",20.00
9,190871,Neymar Jr,29,Brazil,91,91,Paris Saint-Germain,"129,000,000.00","270,000.00",2183,Right,5.00,5.00,5.00,High/ Medium,Unique,"<span class=""pos pos27"">LW",10.00,"Aug 3, 2017",NaN,2025,175.00,68.00,85.00,83.00,63.00,86.00,86.00,95.00,88.00,87.00,81.00,95.00,93.00,89.00,96.00,89.00,84.00,80.00,64.00,81.00,53.00,81.00,63.00,37.00,86.00,90.00,93.00,93.00,NaN,32.00,29.00,9.00,9.00,15.00,15.00,11.00,LW,91.00,"2,387,000,000.00",35.00
10,165153,K. Benzema,33,France,89,89,Real Madrid CF,"66,000,000.00","350,000.00",2116,Right,4.00,4.00,4.00,Medium/ Medium,Normal (170-185),"<span class=""pos pos21"">CF",9.00,"Jul 9, 2009",NaN,2023,185.00,81.00,75.00,90.00,89.00,86.00,86.00,87.00,81.00,73.00,73.00,90.00,77.00,75.00,79.00,91.00,72.00,85.00,79.00,78.00,82.00,79.00,63.00,39.00,90.00,87.00,84.00,90.00,NaN,24.00,18.00,13.00,11.00,5.00,5.00,7.00,CF,89.00,"1,353,000,000.00",43.00
11,211688,Gayà,26,Spain,83,86,Valencia CF,"435,000,000.00","48,000.00",2097,Left,3.00,3.00,4.00,High/ Medium,Lean (170-185),"<span class=""pos pos7"">LB",14.00,"Sep 13, 2012",NaN,2023,172.00,66.00,80.00,61.00,58.00,81.00,58.00,79.00,80.00,49.00,75.00,82.00,81.00,85.00,82.00,84.00,78.00,62.00,53.00,87.00,66.00,59.00,76.00,80.00,76.00,75.00,52.00,76.00,NaN,82.00,84.00,13.00,10.00,9.00,12.00,9.00,LWB,85.00,"946,000,000.00",79.00
12,206113,S. Gnabry,25,Germany,85,86,FC Bayern München,"645,000,000.00","110,000.00",2080,Right,4.00,4.00,4.00,High/ Medium,Unique,"<span class=""pos pos12"">RM",7.00,"Jul 1, 2017",NaN,2023,176.00,77.00,74.00,86.00,42.00,82.00,83.00,88.00,74.00,62.00,78.00,83.00,90.00,77.00,87.00,86.00,88.00,87.00,65.00,78.00,68.00,82.00,63.00,38.00,86.00,83.00,68.00,80.00,NaN,44.00,43.00,14.00,10.00,10.00,9.00,7.00,RM,85.00,"1,113,000,000.00",45.00
13,121939,17 P. Lahm,32,Germany,88,88,FC Bayern München,"295,000,000.00","200,000.00",2146,Right,4.00,3.00,3.00,Medium/ High,Normal (170-),"<span class=""pos pos3"">RB",21.00,"Nov 1, 2002",NaN,2018,170.00,66.00,84.00,47.00,63.00,86.00,66.00,82.00,77.00,59.00,77.00,86.00,68.00,67.00,82.00,91.00,93.00,57.00,72.00,79.00,59.00,65.00,58.00,93.00,69.00,82.00,69.00,94.00,86.00,87.00,95.00,11.00,12.00,5.00,14.00,5.00,RWB,85.00,NaN,NaN
14,200389,J. Oblak,28,Slovenia,91,93,Atlético de Madrid,"112,000,000.00","130,000.00",1413,Right,5.00,3.00,1.00,Medium/ Medium,Unique,"<span class=""pos pos0"">GK",13.00,"Jul 16, 2014",NaN,2023,188.00,87.00,13.00,11.00,15.00,43.00,13.00,12.00,13.00,14.00,40.00,30.00,43.00,60.00,67.00,88.00,49.00,59.00,78.00,41.00,78.00,12.00,34.00,19.00,11.00,65.00,11.00,68.00,NaN,12.00,18.00,87.00,92.00,78.00,90.00,90.00,GK,91.00,"238,000,000.00",27.00

### Ratio of Wage and Vale vs Overall Rating

In [141]:
ratings_ratio = df.groupby('Club').mean()[['Best Overall Rating','Value','Wage']].reset_index().sort_values('Best Overall Rating', ascending = False)

ratings_ratio['ratio_wage'] = ratings_ratio['Wage'] / ratings_ratio['Best Overall Rating']
ratings_ratio['ratio_value'] = ratings_ratio['Value'] / ratings_ratio['Best Overall Rating']
ratings_ratio

,Club,Best Overall Rating,Value,Wage,ratio_wage,ratio_value
8,111648,89.00,0.00,0.00,0.00,0.00
467,Juventus,79.70,"95,151,515.15","69,000.00",865.78,"1,193,916.35"
312,FC Bayern München,79.64,"147,996,212.12","75,242.42",944.82,"1,858,399.92"
592,Paris Saint-Germain,79.10,"172,114,634.15","81,109.76","1,025.44","2,175,979.03"
306,FC Anzhi Makhachkala,79.00,0.00,"30,000.00",379.75,0.00
...,...,...,...,...,...,...
376,Finn Harps,55.54,"249,230.77",500.00,9.00,"4,487.53"
867,ŁKS Łódź,53.00,"60,000.00",500.00,9.43,"1,132.08"
370,Falkenbergs FF,53.00,"170,000.00",500.00,9.43,"3,207.55"
260,Dagenham and Redbridge,51.00,"60,000.00",500.00,9.80,"1,176.47"
70,Arezzo,36.00,0.00,0.00,0.00,0.00

In [162]:
ratings_ratio.sort_values('ratio_wage', ascending=False).head(10)

,Club,Best Overall Rating,Value,Wage,ratio_wage,ratio_value
637,Real Madrid CF,76.87,"128,493,421.05","118,078.95","1,536.12","1,671,602.19"
525,Manchester City,76.00,"241,070,135.14","98,408.11","1,294.84","3,171,975.46"
511,Liverpool,76.91,"127,094,285.71","95,028.57","1,235.51","1,652,414.56"
309,FC Barcelona,77.88,"102,625,000.00","93,125.00","1,195.83","1,317,817.01"
526,Manchester United,78.78,"210,705,634.15","91,560.98","1,162.23","2,674,591.64"
177,Chelsea,77.14,"173,436,805.56","85,805.56","1,112.35","2,248,370.54"
592,Paris Saint-Germain,79.10,"172,114,634.15","81,109.76","1,025.44","2,175,979.03"
312,FC Bayern München,79.64,"147,996,212.12","75,242.42",944.82,"1,858,399.92"
455,Inter,77.21,"79,996,690.48","68,380.95",885.60,"1,036,034.84"
467,Juventus,79.70,"95,151,515.15","69,000.00",865.78,"1,193,916.35"

In [147]:
ratings_ratio.sort_values('ratio_value', ascending=False).head(10)

,Club,Best Overall Rating,Value,Wage,ratio_wage,ratio_value
525,Manchester City,76.00,"241,070,135.14","98,408.11","1,294.84","3,171,975.46"
526,Manchester United,78.78,"210,705,634.15","91,560.98","1,162.23","2,674,591.64"
177,Chelsea,77.14,"173,436,805.56","85,805.56","1,112.35","2,248,370.54"
592,Paris Saint-Germain,79.10,"172,114,634.15","81,109.76","1,025.44","2,175,979.03"
312,FC Bayern München,79.64,"147,996,212.12","75,242.42",944.82,"1,858,399.92"
780,Tottenham Hotspur,75.03,"131,741,666.67","61,194.44",815.62,"1,755,905.22"
637,Real Madrid CF,76.87,"128,493,421.05","118,078.95","1,536.12","1,671,602.19"
511,Liverpool,76.91,"127,094,285.71","95,028.57","1,235.51","1,652,414.56"
87,Atlético de Madrid,78.16,"124,267,567.57","56,513.51",723.03,"1,589,868.60"
662,Rubin Kazan,75.00,"115,000,000.00","50,000.00",666.67,"1,533,333.33"

### Player with the most potential

In [161]:
promising_players = df[['ID', 'Name', 'Age','Club','Best Position','Best Overall Rating', 'Potential','Value', 'Wage']]
promising_players['future_growth'] = promising_players['Potential'] - promising_players['Best Overall Rating']
promising_players.sort_values(['future_growth', 'Potential'], ascending = False).head(20)

C:\Users\T-Gamer\AppData\Local\Temp/ipykernel_13408/3409219545.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  promising_players['future_growth'] = promising_players['Potential'] - promising_players['Best Overall Rating']

,ID,Name,Age,Club,Best Position,Best Overall Rating,Potential,Value,Wage,future_growth
16504,263316,C. Chatzigavriel,17,NaN,GK,58.00,84,0.00,0.00,26.00
16694,260982,C. Brady,17,Chicago Fire Football Club,GK,51.00,77,"220,000.00",500.00,26.00
16696,255336,F. Emmings,17,Minnesota United FC,GK,48.00,73,"130,000.00",500.00,25.00
14416,260181,21 A. Ferguson,16,St. Johnstone FC,ST,52.00,76,"190,000.00",500.00,24.00
11200,251187,P. Dwomoh,17,Royal Antwerp FC,CAM,62.00,85,"775,000.00",500.00,23.00
14750,260192,A. Hackford,17,Sheffield United,ST,61.00,84,"700,000.00",950.00,23.00
11295,264180,A. Devine,16,Tottenham Hotspur,CAM,59.00,82,"500,000.00","1,000.00",23.00
14128,256598,21 S. Auklend,17,Viking FK,CAM,57.00,80,"450,000.00",500.00,23.00
14530,254819,K. Urbański,16,Bologna,CAM,55.00,78,"300,000.00",550.00,23.00
15001,263294,A. Denholm,17,Heart of Midlothian,RM,54.00,77,"250,000.00",500.00,23.00
15113,263090,J. Eng,16,Vålerenga Fotball,RW,53.00,76,"300,000.00",500.00,23.00
16619,256609,J. Guadagno,18,F.C. København,GK,53.00,76,"275,000.00",500.00,23.00
15147,261677,R. O'Kane,17,Dundalk FC,RW,52.00,75,"180,000.00",500.00,23.00
14496,260912,O. Cisneros,17,Sporting Kansas City,CAM,51.00,74,"150,000.00",500.00,23.00
16697,264057,J. Nieuwenhuizen,17,Melbourne City FC,GK,51.00,74,"170,000.00",500.00,23.00
14595,259442,R. van den Berg,16,PEC Zwolle,CB,61.00,83,"675,000.00",500.00,22.00
16599,250831,C. Boyce-Clarke,18,Reading,GK,59.00,81,"650,000.00",500.00,22.00
16267,244483,21 M. Gasparini,18,Udinese Calcio,GK,57.00,79,"475,000.00",500.00,22.00
16568,252995,V. Torop,17,PFC CSKA Moscow,GK,53.00,75,"275,000.00",500.00,22.00
15642,259129,K. Paulsen,17,Viking FK,CB,52.00,74,"140,000.00",500.00,22.00

In [160]:
promising_players.sort_values(['future_growth', 'Potential'], ascending = False)[promising_players['Potential'] > 80].head(20)

C:\Users\T-Gamer\AppData\Local\Temp/ipykernel_13408/2322751781.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  promising_players.sort_values(['future_growth', 'Potential'], ascending = False)[promising_players['Potential'] > 80].head(20)

,ID,Name,Age,Best Position,Best Overall Rating,Potential,Value,Wage,future_growth
16504,263316,C. Chatzigavriel,17,GK,58.00,84,0.00,0.00,26.00
11200,251187,P. Dwomoh,17,CAM,62.00,85,"775,000.00",500.00,23.00
14750,260192,A. Hackford,17,ST,61.00,84,"700,000.00",950.00,23.00
11295,264180,A. Devine,16,CAM,59.00,82,"500,000.00","1,000.00",23.00
14595,259442,R. van den Berg,16,CB,61.00,83,"675,000.00",500.00,22.00
16599,250831,C. Boyce-Clarke,18,GK,59.00,81,"650,000.00",500.00,22.00
12985,261025,D. Scarlett,17,ST,65.00,86,"15,000,000.00","3,000.00",21.00
11634,263620,R. Lavia,17,CB,64.00,85,"12,000,000.00",700.00,21.00
13102,258315,21 B. Arrey-Mbi,17,CB,64.00,85,"12,000,000.00",500.00,21.00
10929,254752,20 S. Hansen,17,RW,63.00,84,"800,000.00",850.00,21.00
11441,260910,S. Shoretire,17,CAM,63.00,84,"12,000,000.00","2,000.00",21.00
10926,259420,21 Bruno Iglesias,17,CM,62.00,83,"700,000.00","2,000.00",21.00
13927,262641,D. Touré,18,ST,62.00,83,"775,000.00","3,000.00",21.00
14518,255558,21 E. Bayram,17,CB,62.00,83,"725,000.00",500.00,21.00
13605,264219,E. Poku,17,RW,61.00,82,"1,000,000.00",500.00,21.00
11509,264209,L. Bogarde,17,CB,60.00,81,"600,000.00",500.00,21.00
16137,245787,21 Iván Martínez,18,GK,60.00,81,"700,000.00",500.00,21.00
9199,260144,C. Patino,17,CDM,65.00,85,"12,000,000.00","2,000.00",20.00
9632,258171,H. Mejbri,18,CAM,64.00,84,"13,000,000.00","6,000.00",20.00
12156,263370,V. Barco,16,LB,63.00,83,"13,000,000.00",500.00,20.00